### ISSUE TITLE
gicjob.com/jobs； gicjob.com/intentions  都被浏览器判定为此链接不安全。给人感觉不好

### ISSUE THREAD

**Issue by arlum** [UReact/HC_feedback#127]
不同的浏览器都是

<img width="490" alt="微信截图_20190821092351" src="https://user-images.githubusercontent.com/47769588/63396533-f5d28b80-c3f9-11e9-8e02-b3378283d95e.png">

**Comment by arlum** [comment]
<img width="584" alt="微信截图_20190821092416" src="https://user-images.githubusercontent.com/47769588/63396608-3500dc80-c3fa-11e9-9faa-440a8f90ff89.png">

**Comment by jimmywong123** [comment]
已解决
