### ISSUE TITLE
Google分析追踪代码（正文）; 百度广告转化追踪代码（附件）-- 恳请十 一 前放进去

### ISSUE THREAD

**Issue by arlum** [UReact/HC_feedback#143]
Website Tracking
Global Site Tag (gtag.js)
This is the Global Site Tag (gtag.js) tracking code for this property. Copy and paste this code as the first item into the <HEAD> of every webpage you want to track. If you already have a Global Site Tag on your page, simply add the config line from the snippet below to your existing Global Site Tag.

==================================================================================

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-56511619-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-56511619-1');
</script>

==================================================================================
The Global Site Tag provides streamlined tagging across Google’s site measurement, conversion tracking, and remarketing products – giving you better control while making implementation easier. By using gtag.js, you will be able to benefit from the latest dynamic features and integrations as they become available. Learn more

[百度广告 转化 代码和说明文档.txt](https://github.com/UReact/HC_feedback/files/3644897/default.txt)

**Comment by jimmywong123** [comment]
已添加
