### ISSUE TITLE
谷歌广告，转化追踪代码。我们已经安装了 Google Analytics（分析），所以请看对应的部分

### ISSUE THREAD

**Issue by arlum** [UReact/HC_feedback#162]
我们已经安装了 Google Analytics（分析）所以第1步用红框这里的方式
![图片](https://user-images.githubusercontent.com/47769588/67174791-069d7e80-f3f6-11e9-9dd6-27f891b1030d.png)

=================================
由于原邮件复制过来会失去格式，很难阅读，所以我转发到 jimmy@hiredchina.com

**Comment by jimmywong123** [comment]
已添加
