### ISSUE TITLE
Can't open (无法打开)

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/HC_feedback#29]
如果您的电脑或者手机打开本系统是一直白屏，请把您的手机型号及浏览器类型发到这里。
If your computer or mobile phone is open this system is always white screen, please send your mobile phone model and browser type here.

**Comment by ThomasLiu** [comment]
![wechatimg34](https://user-images.githubusercontent.com/3435615/53391072-29df6d80-39d0-11e9-9295-3c1d0c7ba659.jpeg)

**Comment by kahyiu** [comment]
![default](https://user-images.githubusercontent.com/48083589/53707070-3f3d1780-3e68-11e9-96fc-6e3133adb855.png)

**Comment by kahyiu** [comment]
win7  谷歌

**Comment by kahyiu** [comment]
win10 Google

**Comment by kahyiu** [comment]
win7 Google

**Comment by arlum** [comment]
Microsoft EdgeHTML 17.17134

Win 10  PC

白屏

**Comment by arlum** [comment]
职位页面，用win7系统-微信浏览器，打开只能看到如下界面
链接：https://www.hiredchina.com/jobs/apple_music_featured_content_reviewer_1552464868272

另外，ECHO的二维码应该换成Kammy的啦
![图片](https://user-images.githubusercontent.com/47769588/54330091-5d1c3080-464f-11e9-9d23-abbc66f1dc75.png)

**Comment by kahyiu** [comment]
苹果6  白屏
