### ISSUE TITLE
404 Report (404汇报)

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/HC_feedback#30]
如果你打开了某个界面是出现 404 提示，请提供一下你在哪里点击的截图（全屏）。方便我们更快解决问题，谢谢～ 

If you open a page that is a 404 message appears, please provide a screenshot of where you clicked (full screen). Convenient for us to solve the problem faster, thank you ~

**Comment by arlum** [comment]
据称，她进入这个页面：http://www.hiredchina.com/jobs?areaId=4&postId=17 之后，点login，就出现 404 状况。
她说的不是login之后，而是不能login直接404；
用的是微信浏览器。
![default](https://user-images.githubusercontent.com/47769588/53719001-cfdf1c00-3e97-11e9-9d93-9be8a9fbef93.png)

**Comment by ThomasLiu** [comment]
@arlum 无法重现
