### ISSUE TITLE
hiredchina页面最底下点击“搜索职位” 跳转失败 不能完全显示

### ISSUE THREAD

**Issue by LucyJoo** [UReact/HC_feedback#33]

**Comment by ThomasLiu** [comment]
@LucyJoo 请提供截图

**Comment by LucyJoo** [comment]
![image](https://user-images.githubusercontent.com/47232757/53462689-b006bd00-3a7f-11e9-833c-6cf05547a980.png)
点击search jobs 过后:
![image](https://user-images.githubusercontent.com/47232757/53462745-dc223e00-3a7f-11e9-85c5-0d0537c471db.png)

**Comment by ThomasLiu** [comment]
@LucyJoo 这个不是 HC 的吧？
