### ISSUE TITLE
重新发布岗位信息后，只能看到新的申请人，旧的岗位申请人查看不了。

### ISSUE THREAD

**Issue by kahyiu** [UReact/HC_feedback#37]
1、网站改版后查看不到之前发布的岗位，系统提示要重新输入岗位信息。
2、重新发布岗位信息后，只能看到新的申请人，旧的岗位申请人查看不了。
![_20190301101413](https://user-images.githubusercontent.com/48083589/53611883-11a76280-3c0b-11e9-8a0c-85311b38bf6b.png)
![_20190301101421](https://user-images.githubusercontent.com/48083589/53611880-11a76280-3c0b-11e9-9b5d-6435f25ba328.png)

**Comment by ThomasLiu** [comment]
@kahyiu 请提供客户 在CRM 内的链接

**Comment by kahyiu** [comment]
> 
> 
> @kahyiu 请提供客户 在CRM 内的链接
http://login.hiredchina.com/invite/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImNvbXBhbnlJZCI6IjU0MjAiLCJ1c2VySWQiOjMzNjQ5fSwiZXhwIjoxNTUyMDExNjU5LCJpYXQiOjE1NTE0MDY4NTl9.FqDwl84wvolaDQs5tQMJJZ6fNpNnpekJKdCmQqUGuS4/company

**Comment by kahyiu** [comment]
> 
> 
> @kahyiu 请提供客户 在CRM 内的链接

![_20190301103408](https://user-images.githubusercontent.com/48083589/53612566-d8bcbd00-3c0d-11e9-889a-10ea18e4f768.png)
