### ISSUE TITLE
职位选项是否能按岗位的发布顺序来排序？

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/HC_feedback#38]
职位选项是否能按岗位的发布顺序来排序？有些老岗位都在岗位选项的顶端，我这边找职位很麻烦

![screen shot 2019-03-01 at 11 01 57 am](https://user-images.githubusercontent.com/47628230/53613673-c5abec00-3c11-11e9-8d73-f88a3ebaa1e5.png)

**Comment by ThomasLiu** [comment]
@Victoryliu1160  按最后的跟进时间排序
