### ISSUE TITLE
网站打不开

### ISSUE THREAD

**Issue by kahyiu** [UReact/HC_feedback#39]
![_20190301140231](https://user-images.githubusercontent.com/48083589/53619703-3a3f5480-3c2b-11e9-8e5d-c111f7f2b601.png)
![_20190301140332](https://user-images.githubusercontent.com/48083589/53619710-40cdcc00-3c2b-11e9-879d-e4b30ee4d4ca.png)

**Comment by ThomasLiu** [comment]
@kahyiu 
Duplicate of #29
亲，需要了解客户的浏览器具体是哪个类型的浏览器

**Comment by kahyiu** [comment]
什么叫哪个类型的浏览器

------------------------------------------------------------------
发件人：Thomas Lau <notifications@github.com>
发送时间：2019年3月4日(星期一) 10:15
收件人：UReact/HC_feedback <HC_feedback@noreply.github.com>
抄　送：Ella <ella.yao@hiredchina.com>; Mention <mention@noreply.github.com>
主　题：Re: [UReact/HC_feedback] 网站打不开 (#39)

@kahyiu
 Duplicate of #29
 亲，需要了解客户的浏览器具体是哪个类型的浏览器
