### ISSUE TITLE
新建职位页面的back按钮

### ISSUE THREAD

**Issue by jimmywong123** [UReact/HC_feedback#4]
![1550399289704](https://user-images.githubusercontent.com/42126331/52911668-de4b0680-32e1-11e9-9c66-2588a6fd8965.jpg)
如果用户是从新建公司的界面过来的，则back按钮应返回新建公司页面；
如果用户是从下图的企业界面过来的，则back按钮应返回下图的企业页面。
![1550399435302](https://user-images.githubusercontent.com/42126331/52911693-2ff39100-32e2-11e9-9831-514b2af34416.jpg)

**Comment by ThomasLiu** [comment]
忽略
