### ISSUE TITLE
企业logo显示/补白问题

### ISSUE THREAD

**Issue by arlum** [UReact/HC_feedback#40]
新上传的企业logo，不能自动补白。一旦logo图片长宽比不是1：1，就会显示不全（如截图）。而且，如果按照以前的自动补白，又会压缩得模糊。需要修正
![default](https://user-images.githubusercontent.com/47769588/53623091-f81c1000-3c36-11e9-8ca0-2782d0a952cd.png)

**Comment by jimmywong123** [comment]
暂时忽略。

**Comment by jimmywong123** [comment]
现在超出部分会自动补白。
![image](https://user-images.githubusercontent.com/42126331/54421278-17429380-4747-11e9-9c95-6d3038567edd.png)
