### ISSUE TITLE
404

### ISSUE THREAD

**Issue by kahyiu** [UReact/HC_feedback#47]
![default](https://user-images.githubusercontent.com/48083589/53949467-0e2d4300-4105-11e9-85ad-37239db33d91.png)
手机型号：Samsung s8

**Comment by ThomasLiu** [comment]
@kahyiu 亲，需要把操作流程描述一下才可以知道什么情况。就在那个用户，在那个界面，点击了什么后，出现这个问题

**Comment by ThomasLiu** [comment]
Duplicate of #30
