### ISSUE TITLE
用AlexWang的账号登录，购买个人简历的时候，总是弹出错误提醒“模块不正确”。

### ISSUE THREAD

**Issue by alexwang2019** [UReact/HC_feedback#49]
![image](https://user-images.githubusercontent.com/47736823/54007622-b262c880-419d-11e9-8b76-b2b537963ba3.png)

**Comment by ThomasLiu** [comment]
@alexwang2019 请提供电话号码，谢谢

**Comment by alexwang2019** [comment]
> @alexwang2019 请提供电话号码，谢谢

13410900995
