### ISSUE TITLE
在给企业用户发送绑定邀请的时候，1、只能发一个链接，不能转换链接。2、转换的链接上面HiredChina.com invite 改为：在华外国人才网 邀请您使用。3、点击进去后，默认中文版本。

### ISSUE THREAD

**Issue by alexwang2019** [UReact/HC_feedback#52]
在给企业用户发送绑定邀请的时候，
1、只能发一个链接，不能转换链接。
2、转换的链接上面HiredChina.com invite 改为：在华外国人才网 邀请您使用。
3、点击进去后，默认中文版本。
![image](https://user-images.githubusercontent.com/47736823/54113317-f87c8e00-4422-11e9-8aa8-aead9666eff5.png)

**Comment by ThomasLiu** [comment]
多一个 中文的邀请链接，还有二维码

**Comment by jimmywong123** [comment]
已经添加中文邀请链接

**Comment by jimmywong123** [comment]
现在可以发送中英文两种邀请链接，以及邀请二维码。
![image](https://user-images.githubusercontent.com/42126331/55700910-c18a9f80-5a03-11e9-86c2-c122fcc50089.png)
