### ISSUE TITLE
不少平台用户反应，手机收不到验证码；邮箱收不到验证邮件。有时候即使收到了，也是很滞后。收到验证码输入后显示“验证码错误”。

### ISSUE THREAD

**Issue by alexwang2019** [UReact/HC_feedback#75]

**Comment by ThomasLiu** [comment]
@alexwang2019 一些国家收不到我们手机的验证码，我们也没有办法。
邮箱的验证码已经调成有效期30分钟。邮件给弄到垃圾箱，我们也没有办法。
你要邮件大概率不到垃圾箱。这里你要砸钱才可以。
你说显示验证码错误，只要验证码超过有效时间才会有可能。
刚刚就测试过，邮件验证码和短信验证码，都正常。
