### ISSUE TITLE
手机端--主页页面底部看不到我们公司的联系信息

### ISSUE THREAD

**Issue by arlum** [UReact/HC_feedback#81]
就本来放在“关于我们”下面的 邮箱和电话，在窄屏之后就没法看见。调整一下显示吧，这个信息还是比较有用的。

![图片](https://user-images.githubusercontent.com/47769588/54803722-a69df880-4cab-11e9-92e1-a5851eaf8800.png)

**Comment by ThomasLiu** [comment]
移动端底部样式更换
