### ISSUE TITLE
候选人信息显示错误

### ISSUE THREAD

**Issue by kahyiu** [UReact/HC_feedback#82]
![图片](https://user-images.githubusercontent.com/48083589/54892460-9aed4480-4eec-11e9-9911-31fc020eb9bd.png)
![图片](https://user-images.githubusercontent.com/48083589/54892468-a17bbc00-4eec-11e9-8af8-d065d299e342.png)

**Comment by ThomasLiu** [comment]
@kahyiu 下次把链接也发上来
