### ISSUE TITLE
网站部分区域字体颜色调整

### ISSUE THREAD

**Issue by jimmywong123** [UReact/HC_feedback#9]
网站的部分区域字体颜色普遍偏淡，建议加深颜色，方便用户阅读。
有一部分的用户屏幕质量较差，如果字体颜色很浅会导致难以阅读。
![image](https://user-images.githubusercontent.com/42126331/52923607-9240a600-3363-11e9-9cb5-2f42d5b158e2.png)

**Comment by ThomasLiu** [comment]
忽略
